### ISSUE TITLE
no bower package

### ISSUE THREAD

**Issue by krystyna93** [heimrichhannot/bootstrap-select#1]
Hi, 
There is no bower package available for this alternate version of silvio moreto's bootstrap-select. I had to add it manually to VS, but is there a bower package you could create?

**Comment by fatcrobat** [comment]
Hi, i recently created a bower package with the name `bootstrap-select-bs4`. 
Please let me know if something is wrong with.

**Comment by los93sol** [comment]
Is there an NPM package?

**Comment by krystyna93** [comment]
Hi Adam,

Bootstrap 4 has stopped compatibility with the bower utility.
You will have to manually install the files yourself into your environment.
I am currently still using Bootstrap 4.0, and not upgraded to 4.2 as yet.

Peace!

**Comment by krystyna93** [comment]
Oh, for Bootstrap select, use
https://github.com/heimrichhannot/bootstrap-select
Its compatible with Bootstrap 4 beta version. I am also using it in my
current project, and all works fine :)

**Comment by fatcrobat** [comment]
@los93sol i have no experience with the nmp manager, tell me the commands and i can create a package. As site note mentioned that official bootstrap-select bs4 release should be released soon.

**Comment by fatcrobat** [comment]
@los93sol There is a contribution npm package `bootstrap4-select-rails`. Check this post https://github.com/heimrichhannot/bootstrap-select/issues/1#issuecomment-348937910.
