### ISSUE TITLE
Example test.html dropdown list not render properly

### ISSUE THREAD

**Issue by dwade0o** [heimrichhannot/bootstrap-select#2]
![test-page-dropdown-not-render](https://user-images.githubusercontent.com/8980040/31748918-021d13f2-b4d3-11e7-81de-9349235e557f.PNG)

![test-page-dropdown-not-render-2](https://user-images.githubusercontent.com/8980040/31749012-ba71d9ba-b4d3-11e7-8eed-7f2fd3ebf835.PNG)

Hi,

I have downloaded your example code from master and give it a try. Looks like the dropdown list is not rendered properly
Please see the attached. When open the dropdown and click on any items, there is no tick to indicate which item has been clicked.

I have tried with different browsers such as Firefox and Chrome (both with latest version), they all appear to be the same.

Thanks.

**Comment by fatcrobat** [comment]
Adjusted the test.html file, bootstrap 4 css/js was missing and font-awesome
