### ISSUE TITLE
change style via options

### ISSUE THREAD

**Issue by reimax** [heimrichhannot/bootstrap-select#3]
i try set default settings:

`
$('.selectpicker').selectpicker({'container': 'body', 'size': 4, 'style':'btn-info'});
`

but on my page style not change to my variant and stay btn-light.

**Comment by fatcrobat** [comment]
Cant reproduce, we did not change anything on the setStyle() behavior. Did you include the `dist/js/bootstrap-select.js` or `dist/js/bootstrap-select.min.js`? Or did you mean the actionbox buttons (select/deselect all) or done button?

**Comment by reimax** [comment]
Of course they are connected, I can see that the select works, but the styles assigned to it did not apply via 'style':'btn-info'. If they are assigned to each select in the template, then everything works.

i have default select:
`
<select class="selectpicker"></select>
`

**Comment by fatcrobat** [comment]
Hey, why did you close this issue? Solved?
