### ISSUE TITLE
live search reposition

### ISSUE THREAD

**Issue by Wuild** [heimrichhannot/bootstrap-select#4]
Just checking if its just me.
When using a very large list and it goes into dropup mode, when searching the list the menu doesn't reposition to the toggle button untill the window is resized
**When using bootstrap 4**
![position1](https://user-images.githubusercontent.com/381189/32348707-f0655a1e-c014-11e7-8680-082da76dfce3.png)
![position2](https://user-images.githubusercontent.com/381189/32348710-f2474a86-c014-11e7-9c23-f12fc2bf7c0f.png)

**Comment by fatcrobat** [comment]
Not easy to debug as popper.js only updates position on window resize or window scroll event. Fixed it by trigger the resize event on the dropdown ownerDocument. Fixed in v1.12.10.

**Comment by Wuild** [comment]
Awesome, i fixed it temporary by setting an interval on all dropdown-menus and just updated the position since i had the same problem with bootstrap datetimepicker. But good work on the fix!
