### ISSUE TITLE
optgroup dividers

### ISSUE THREAD

**Issue by Wuild** [heimrichhannot/bootstrap-select#5]
The library is adding selectable dividers when using optgroup.
Im guessing the problem is that its an A element that makes it selectable... just wanted to let you know.
**PS. the divider class in BS4 has been changed to dropdown-divider**
![dividers](https://user-images.githubusercontent.com/381189/32398200-114a9184-c0ee-11e7-9df7-9fd895692835.png)

**Comment by Wuild** [comment]
Fixed it my self: #6

**Comment by fatcrobat** [comment]
Thanks, merged it.
